# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zenni' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for zenni

  target 'zenni-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'zenniTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'zenni-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for zenni-tvOS

  target 'zenni-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
